name: Flutter CD

on:
  push:
    tags:
      - 'v*'

jobs:
  build_and_deploy_android:
    name: Build and Deploy Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
      - run: flutter pub get
      
      # Setup Firebase CLI
      - name: Setup Firebase CLI
        run: npm install -g firebase-tools
      
      # Build Android App Bundle
      - name: Build Android App Bundle
        run: flutter build appbundle --release
      
      # Upload to Firebase App Distribution
      - name: Upload to Firebase App Distribution
        run: |
          firebase appdistribution:distribute build/app/outputs/bundle/release/app-release.aab \
            --app ${{ secrets.FIREBASE_ANDROID_APP_ID }} \
            --token ${{ secrets.FIREBASE_TOKEN }} \
            --groups "testers" \
            --release-notes "Automatic build via GitHub Actions"
  
  build_ios:
    name: Build iOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
      - run: flutter pub get
      
      # Build iOS
      - name: Build iOS
        run: flutter build ios --release --no-codesign
      
      # Note: For actual iOS deployment, you would need to set up code signing
      # and additional steps for App Store Connect or TestFlight
      
  build_web:
    name: Build and Deploy Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
      - run: flutter pub get
      
      # Enable web
      - name: Enable Web
        run: flutter config --enable-web
      
      # Build Web
      - name: Build Web
        run: flutter build web --release
      
      # Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
